#!/bin/sh

if [ $# -ne 1 ]; then
    echo "Usage: $0 log-file"
    exit 1
fi

while true
do
  cp $1 /tmp
  egrep "saved|Average" $1 > /tmp/$1.avg
  grep ROOM $1 > /tmp/$1.ROOMS
  grep OHL  $1 > /tmp/$1.OHL
  python plot.py $1 --save
  mv $1*png /tmp
  sleep 300
done
