#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Usage: $0 rom-option-set-name"
    exit 1
fi

program="a3c.py"
case $1 in
  "montezuma")
    rom="montezuma_revenge.bin"
    option="--train-episode-steps=30 --lives-lost-reward=-0.02 --psc-use=True --repeat-action-probability=0.0 --randomness-time=3000 --end-mega-step=80 --save-mega-interval=3 --log-interval=800 "
    ;;
  "breakout")
    rom="breakout.bin"
    option=""
    ;;
  *)
    echo "Invalid option-set-name: $1"
    exit 1
    ;;
esac

echo "rom=$rom"
echo "option=$option"

. activate tensorflow
python $program --rom $rom $option 


