#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Usage: $0 rom-option-set-name"
    exit 1
fi

case $1 in
  "latest")
    rom="montezuma_revenge.bin"
    option="--action-size=18 --train-episode-steps=150 --lives-lost-reward=0.0 --reset-max-reward=True --record-new-record-dir=new-record --psc-use=True --repeat-action-probability=0.0 --randomness-time=3000 --color-maximizing-in-gs=True --color-averaging-in-ale=False --use-gpu=False";;
  "prev")
    rom="montezuma_revenge.bin"
    option="--action-size=18 --train-episode-steps=150 --lives-lost-reward=-0.1 --reset-max-reward=True --record-new-record-dir=new-record --psc-use=True --repeat-action-probability=0.0 --randomness-time=3000";;
  "montezuma")
    rom="montezuma_revenge.bin"
    option="--action-size=18 --train-episode-steps=4500 --lives-lost-reward=0.0 --reward-clip=0.0 --reset-max-reward=True --record-new-record-dir=new-record";;
  "breakout")
    rom="breakout.bin"
    option="";;
  *)
    echo "Invalid option-set-name: $optionsn"
    exit 1;;
esac

echo "rom=$rom"
echo "option=$option"

#. activate tensorflow
python a3c.py --rom $rom $option 


